### ISSUE TITLE
Standalone and uart weld picture is not clear

### ISSUE THREAD

**Issue by sl1pkn07** [bigtreetech/BIGTREETECH-TMC2208-V3.0#1]
Hi

according the pdf. the pictures about weld the J2 pads for switch standalone drivers to uart drivers is not clear at all

what is the standalone, and what is the UART picture?

i can assume the left picture is the standalone version, and the rigth the UART version?

![Screenshot_20190904_213935](https://user-images.githubusercontent.com/462213/64285764-806bcc80-cf5c-11e9-9457-b91e497afcf1.png)

if the v3.0, not have asigned the work mode*, what is the state of the J2 pin? all J2 pads unweld?

*
![Screenshot_20190904_213824](https://user-images.githubusercontent.com/462213/64285699-57e3d280-cf5c-11e9-906d-d8ab8845a691.png)

greetings

**Comment by bwaldrum** [comment]
The best explanation I have seen for the difference in the two pictures is in this BIGTREETCH video at 1:33

https://youtu.be/k3Uc1F5jgVQ?t=93

**Comment by sl1pkn07** [comment]
![Screenshot_20190925_183522](https://user-images.githubusercontent.com/462213/65621049-44f47900-dfc3-11e9-9e80-c69fd49a75e9.png)


with this pic. now all is crear

close
