### ISSUE TITLE
TMC2208 V3.0 on SKR1.3 ALL LOW error

### ISSUE THREAD

**Issue by KixMan28** [bigtreetech/BIGTREETECH-TMC2208-V3.0#2]
Today I upgraded the main board to BTT SKR 1.3 with BTT TMC2208 V3.0 in UART mode, with the latest Marlin 2.0.X firmware and MKS TFT28 V4.0 display. I have the following issue with this setup:
- if I run M122 in Pronterface I get ALL IN LOW error message on all axis

`
SENDING:M122
		X	Y	Z	E
Enabled		false	false	false	false
Set current	600	600	800	500
RMS current	1049	1049	1436	883
MAX current	1479	1479	2025	1245
Run current	18/31	18/31	25/31	15/31
Hold current	9/31	9/31	12/31	7/31
CS actual	0/31	0/31	0/31	0/31
PWM scale	0	0	0	0
vsense		0=.325	0=.325	0=.325	0=.325
stealthChop	false	false	false	false
msteps		256	256	256	256
tstep		0	0	0	0
PWM thresh.	1905	1905	10541	4534
[mm/s]		83	83	3	30
OT prewarn	false	false	false	false
triggered
 OTP		false	false	false	false
off time	0	0	0	0
blank time	16	16	16	16
hysteresis
 -end		-3	-3	-3	-3
 -start		1	1	1	1
Stallguard thrs
DRVSTATUS	X	Y	Z	E
sg_result
stst		*	*	*	*
olb
ola
s2gb
s2ga
otpw
ot
157C
150C
143C
120C
s2vsa
s2vsb
Driver registers:
		X	0x00:00:00:00	 Bad response!
		Y	0x00:00:00:00	 Bad response!
		Z	0x00:00:00:00	 Bad response!
		E	0x00:00:00:00	 Bad response!
Testing X connection... Error: All LOW
Testing Y connection... Error: All LOW
Testing Z connection... Error: All LOW
Testing E connection... Error: All LOW

`

- if I move the motors from Pronterface they move 20 mm instead of 10 mm
- if I auto home X first the Z hoes up 20 mm and the it homes X.

What I have done already:
On the board I have set the jumper on INT-5V. I have jumpers on the UART pins. All the other jumpers are removed. I didn't soldered the pads on the bottom of the TMC2208. In Marlin the drivers are set to TMC2208 and the e-steps are 80.80.400, 95

Please help.

**Comment by KixMan28** [comment]
I have soldered the pads on the bottom of the TMC2208 drivers and after several plugging in and out, finally all drivers were recognized by my SKR1.3 board.

**Comment by MLiv79** [comment]
> I have soldered the pads on the bottom of the TMC2208 drivers and after several plugging in and out, finally all drivers were recognized by my SKR1.3 board.

Hi, could you explain better what you have soldered? Thanks
